version: '3.8'

services:
  unimixer-ota:
    build: .
    container_name: unimixer-ota-server
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      # Persistent storage for firmware files
      - firmware_data:/app/public/firmware
      # Optional: Mount custom config
      - ./config:/app/config:ro
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
      - HOSTNAME=${HOSTNAME:-0.0.0.0}
      # Add custom environment variables here
      - OTA_SERVER_HOST=${OTA_SERVER_HOST:-0.0.0.0}
      - OTA_SERVER_PORT=${OTA_SERVER_PORT:-3000}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-50MB}
      - NEXT_PUBLIC_SERVER_HOST=${NEXT_PUBLIC_SERVER_HOST:-localhost}
      - NEXT_PUBLIC_SERVER_PORT=${NEXT_PUBLIC_SERVER_PORT:-3000}
      - MAX_UPLOAD_SIZE=${MAX_UPLOAD_SIZE:-52428800}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${PORT:-3000}/api/stats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=unimixer-ota"
      - "service.description=UniMixer OTA Firmware Server"

volumes:
  firmware_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/firmware

networks:
  default:
    name: unimixer-network 
